export function generateInitialOrderData() {
  return {
    numero_orden: `OS-${Math.floor(100000 + Math.random() * 900000)}`,
    fecha_emision: new Date().toISOString().split('T')[0],
    hora_emision: new Date().toTimeString().slice(0, 5),
    fecha_entrega: '',
    hora_entrega: '',
    condicion_pago: 'CONTADO',
    datos_cliente: {
      razon_social: '',
      ruc: '',
      direccion: 'CALLE LIBERTAD N° 491 - MORRO SOLAR - JAEN - CAJAMARCA',
      distrito: 'JAEN',
      usuario: '',
      dni: '',
      email: '',
      celular: '980 988 321',
      telefono: '931 429 334'
    },
    datos_vehiculo: {
      modelo: 'HONDA GL 150',
      nro_motor: '',
      nro_chasis: '',
      ano_fab: '2023',
      color: 'ROJO',
      placa: '',
      kilometraje: '12450',
      gasolina: '1/2'
    },
    tipo_servicio: {
      mantenimiento_general: true,
      reparacion_general: false,
      reparacion_parcial: false,
      mantenimiento_preventivo: false,
      servicio_express: false,
      servicio_garantia: false
    },
    trabajos_especificos: {
      mantenimiento: true,
      cambio_aceite: true,
      reparacion_motor: false,
      descarbonizados: false,
      embrague: false,
      transmision: false,
      sistema_arrastre: false,
      frenos: true,
      bateria: false,
      revision_electrico: true,
      revision_encendido: false,
      suspension: false,
      aro_neumatico: false,
      sistema_escape: false,
      sistema_direccion: false,
      otros: ''
    },
    resumen_soles: {
      mo_mantenimiento: 50.00,
      mo_reparacion: 0.00,
      servicio_terceros: 0.00,
      otros_mo: 0.00,
      subtotal_mo: 50.00,
      repuestos: 85.00,
      accesorios: 0.00,
      lubricantes: 35.00,
      otros_repuestos: 0.00,
      subtotal_repuestos: 120.00,
      valor_venta_total: 170.00,
      adelantos: 20.00,
      total_a_pagar: 150.00
    },
    requerimientos_cliente: 'Revisión general de frenos y cambio de aceite de motor.',
    inventario_vehiculo: {
      llave_contacto: true,
      tarjeta_propiedad: true,
      libro_servicio: false,
      espejos_izq: true,
      espejos_der: true,
      tapiz_asiento: true,
      porta_herramientas: true,
      telescopicas: true,
      cobertores: true,
      tapas_laterales_izq: true,
      tapas_laterales_der: true,
      parrilla: true,
      velocimetro: true,
      tacometro: true,
      maletera_delivery: false,
      seguro_cadena: true,
      cable_freno_delantero: true,
      cable_embrague: true,
      cable_velocimetro: true,
      cable_tacometro: true,
      parador_lateral: true,
      parador_central: true,
      cubrecadena: true,
      amortiguadores_post_1: true,
      amortiguadores_post_2: true,
      guardafango_delantero: true,
      guardafango_posterior: true,
      llanta_delantera_buena: true,
      llanta_delantera_gastada: false,
      llanta_posterior_buena: true,
      llanta_posterior_gastada: false,
      pedal_arranque: true,
      pedal_cambio: true,
      tapa_lateral_si: true,
      tapa_lateral_no: false,
      jebe_estribo_izq: true,
      jebe_estribo_der: true,
      descanza_pie_izq: true,
      descanza_pie_der: true,
      faro_delantero: true,
      tapa_gasolina: true,
      herramientas: true,
      varilla_aceite: true,
      tapa_deposito_freno: true,
      escarines: true,
      emblemas: true,
      faros_direccionales_laterales: true,
      faros_posteriores: true,
      pedal_frenos: true,
      otros: ''
    },
    forma_pago: 'EFECTIVO',
    facturacion: {
      tipo: 'BOLETA',
      series: 'B001',
      numeros: '000123'
    },
    firmas: {
      aceptado_cliente_nombre: '',
      aceptado_cliente_dni: '',
      vb_asesor: 'ALONSO V.',
      recibi_conforme_nombre: '',
      recibi_conforme_dni: ''
    },
    repuestos_items: [
      { item: 1, num_parte: 'HON-15410', descripcion: 'FILTRO DE ACEITE HONDA GL150', precio_unitario: 15.00, cantidad: 1, subtotal: 15.00 },
      { item: 2, num_parte: 'LUB-4T10W30', descripcion: 'ACEITE HONDA 4T 10W30 1L', precio_unitario: 35.00, cantidad: 1, subtotal: 35.00 },
      { item: 3, num_parte: 'HON-06455', descripcion: 'PASTILLAS DE FRENO DELANTERO', precio_unitario: 70.00, cantidad: 1, subtotal: 70.00 }
    ],
    terceros_items: [],
    mano_obra_items: [
      { item: 1, descripcion: 'MANTENIMIENTO PREVENTIVO Y REVISIÓN GENERAL', precio_unitario: 50.00, cantidad: 1, subtotal: 50.00 }
    ],
    observaciones: 'Se sugiere cambio de llanta posterior en el próximo mantenimiento.',
    tecnico_responsable: 'ALONSO VARGAS L.',
    hora_inicio: '08:30',
    hora_fin: '11:00',
    fecha_trabajo: new Date().toISOString().split('T')[0]
  };
}
